# Generated by Django 3.2.7 on 2022-03-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
