# Generated by Django 3.2.7 on 2022-03-22 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twits', '0004_twit_user_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twit',
            name='user_like',
        ),
        migrations.AddField(
            model_name='twit',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='twits_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
