# Generated by Django 3.2.7 on 2022-03-25 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twits', '0007_alter_comment_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='users_like',
            field=models.ManyToManyField(related_name='twits_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
