# Generated by Django 4.0.4 on 2022-05-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0008_alter_twit_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
