# Generated by Django 4.0.4 on 2022-05-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0009_alter_twit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
